In [11]:
import pandas as pd
import pygplates
import Utils

input_file_name = 'deposit_positives.csv'
config_file_name = 'config.AREPS.json'


Utils.load_config(config_file_name)
Utils.print_parameters()

data = pd.read_csv(input_file_name)
#display(data)

lons=data['lon']
lats=data['lat']
static_polygons = pygplates.FeatureCollection(Utils.get_parameter('static_polygons_file'))
rotation_model = pygplates.RotationModel(Utils.get_files(Utils.get_parameter('rotation_files')))
plate_ids = Utils.get_plate_id(lons.tolist(), 
                               lats.tolist(), 
                               static_polygons, 
                               rotation_model)

print(plate_ids)
data['plate_id'] = plate_ids
data.to_csv(input_file_name, index=False)
display(data)
print(f'New data has been saved in {input_file_name}.')

the parameters are:
{ 'agegrid_url': '',
  'anchor_plate_id': 0,
  'case_name': 'test-case',
  'coastlines': '../data/Global_EarthByte_230-0Ma_GK07_AREPS_Coastlines.gpmlz',
  'convergence_data_dir': './convergence_data/AREPS/',
  'convergence_data_filename_ext': 'csv',
  'convergence_data_filename_prefix': 'subStats',
  'coreg_input_dir': './coreg_input/AREPS/',
  'coreg_input_files': [ 'positive_deposits.csv',
                         'negative_deposits.csv',
                         'deposit_candidates.csv'],
  'coreg_output_dir': 'coreg_output',
  'feature_names': [ 'dist_nearest_edge',
                     'trench_abs_ortho',
                     'conv_ortho',
                     'conv_paral'],
  'grid_files': [ ( '/data/AgeGrids/Muller_etal_2016_AREPS_v1.17_AgeGrid-{time:d}.nc',
                    'seafloor_age')],
  'machine_learning_engine': 'RFC',
  'map_extent': [],
  'ml_input_dir': 'ml_input',
  'ml_output_dir': 'ml_output',
  'plate_tectonic_tools_path': '/home/mchin/workspaces/machine_learning/spatio-temporal-exploration/python/../PlateTectonicTools/ptt/',
  'region_of_interest_polygon_file': '/home/mchin/workspaces/machine_learning/spatio-temporal-exploration/python/../data/polygon_south_america.csv',
  'regions': [5, 10],
  'rotation_files': ['../data/Global_EarthByte_230-0Ma_GK07_AREPS.rot'],
  'static_polygons_file': '../data/Shapefiles/StaticPolygons/Global_EarthByte_GPlates_PresentDay_StaticPlatePolygons_2015_v1.shp',
  'threshold_sampling_distance_degrees': 0.2,
  'time': {'end': 230, 'start': 0, 'step': 1},
  'topology_files': [ '../data/Global_EarthByte_230-0Ma_GK07_AREPS_PlateBoundaries.gpml.gz',
                      '../data/Global_EarthByte_230-0Ma_GK07_AREPS_Topology_BuildingBlocks.gpml.gz'],
  'vector_files': ['{conv_dir}subStats_{time:.2f}.csv'],
  'velocity_delta_time': 1}
[16112, 16112, 16110, 16110, 16112, 16110, 16112, 16112, 16112, 16112, 16112, 105, 178, 16112, 173, 173, 173, 104, 173, 101, 178, 104, 104, 16124, 173, 101, 101, 101, 104, 104, 104, 101, 104, 215, 215, 104, 16122, 178, 178, 16110, 16110, 101, 16110, 104, 16110, 178, 178, 104, 101, 178, 104, 101, 101, 104, 178, 104, 104, 154, 104, 101, 16101, 16101, 16101, 16101, 16101, 16101, 16101, 104, 16110, 16110, 16110, 16101, 104, 101, 101, 16101, 104, 178, 16101, 16101, 101, 104, 104, 104, 16101, 16101, 16101, 101, 101, 16101, 104, 16101, 16101, 101, 101, 101, 101, 101, 154, 104, 101, 101, 101, 104, 101, 16101, 101, 101, 101, 101, 101, 101, 16105, 101, 104, 101, 101, 16101, 104, 101, 16107, 104, 104, 16101, 101, 16105, 101, 104, 101, 101, 104, 101, 101, 101, 101, 101, 101, 101, 101, 101, 104, 104, 101, 101, 101, 101, 101, 101, 16102, 101, 101, 101, 101, 101, 101, 101, 16101, 101, 101, 101, 101, 101, 101, 101, 104, 101, 154, 101, 104, 101, 101, 101, 101, 16104, 101, 101, 16104, 16105, 16104, 16104, 16102, 16104, 101, 16104, 16104, 101, 16113, 16101, 16101, 16101, 16104, 101, 16105, 16104, 178, 16105, 16101, 178, 101, 101, 16104, 16104, 16104, 101, 18103, 16101, 16104, 16101, 16104, 16104, 16104, 16101, 16101, 16101, 16104, 173, 173, 178, 16101, 18106, 16101, 16101, 16101, 104, 101, 173, 16101, 173, 173, 178, 173, 16101, 16101, 178, 16105, 18106, 101, 16101, 101, 16102, 178, 16104, 16105, 16105, 16105, 16104, 16104, 16101, 178, 178, 16105, 16105, 16101, 178, 16102, 16102, 178, 16110, 178, 105, 16102, 178, 16110, 16110, 16110, 16110, 16110, 16110, 16110, 16102, 178, 16110, 16110, 101, 16101, 16104, 16101, 16102, 16102, 16107, 16101, 16101, 16102, 16102, 16102, 16113, 16102, 16102, 16102, 16102, 16101, 16101, 16101, 16101, 178, 16102, 16102, 16102, 16102, 16102, 16102, 16102, 16102, 16102, 16102, 16113, 16102, 16102, 16101, 16102, 16101]

     index     lon    lat  age  plate_id
0        0 -158.40  56.52    4     16112
1        1 -157.24  57.05    5     16112
2        2 -127.85  50.68    5     16110
3        3 -127.58  50.33    5     16110
4        4 -160.68  55.63    6     16112
..     ...     ...    ...  ...       ...
306    306 -121.05  50.49  210     16102
307    307 -121.00  50.43  210     16102
308    308 -131.88  58.24  218     16101
309    309 -126.68  57.22  221     16102
310    310 -130.99  57.36  222     16101

[311 rows x 5 columns]

New data has been saved in deposit_positives.csv.